# Generated by Django 5.1.6 on 2025-02-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('surname', models.CharField(blank=True, max_length=255, null=True)),
                ('major', models.CharField(max_length=255)),
                ('year_of_study', models.IntegerField()),
                ('faculty', models.CharField(max_length=255)),
            ],
        ),
    ]
